/*
Script generated by Aqua Data Studio 19.0.1-5 on may-22-2023 09:13:31 AM
Database: mdn
Schema: informix
Objects: TABLE, VIEW
*/
CREATE TABLE "informix".insumos  ( 
	id_insumo          	SERIAL NOT NULL,
	nombre             	VARCHAR(50) NOT NULL,
	cantidad_existencia	INTEGER NOT NULL,
	marca_producto     	VARCHAR(50) NOT NULL,
	nombre_proveedor   	VARCHAR(50) NOT NULL,
	precio             	DECIMAL(10,2) NOT NULL,
	PRIMARY KEY(id_insumo)
	ENABLED
)
LOCK MODE ROW;

INSERT INTO "informix".insumos("id_insumo", "nombre", "cantidad_existencia", "marca_producto", "nombre_proveedor", "precio")
  VALUES(1, 'Maiz', 2, 'Maya', 'Manuel Jose', 251.00);
INSERT INTO "informix".insumos("id_insumo", "nombre", "cantidad_existencia", "marca_producto", "nombre_proveedor", "precio")
  VALUES(2, 'Frijol', 15, 'Maya', 'Manuel Jose', 150.00);
INSERT INTO "informix".insumos("id_insumo", "nombre", "cantidad_existencia", "marca_producto", "nombre_proveedor", "precio")
  VALUES(3, 'Incaparina', 150, 'Incaparina', 'Jose Estrada', 15.00);
INSERT INTO "informix".insumos("id_insumo", "nombre", "cantidad_existencia", "marca_producto", "nombre_proveedor", "precio")
  VALUES(4, 'Frijol', 150, 'Incaparina', 'Jose Estrada', 12.00);
